apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
data:
  secrets.json: {{ .Values.secrets_json |toJson }}
{{- if .Values.enable_k8s_auth }}
  policies.json: {{ .Values.policies_json |toJson }}
  k8sroles.json: {{ .Values.k8sroles_json |toJson }}
{{- end -}}