apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
data:
  secrets.json: '{{ .Values.secrets |toJson }}'
{{- if .Values.enable_k8s_auth }}
  policies.json: '{{ .Values.policies |toJson }}'
  k8sroles.json: '{{ .Values.k8sroles |toJson }}'
{{- end -}}