# Default values for vault.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: quay.io/dollarshaveclub/vault-dev
  tag: master
  pullPolicy: IfNotPresent

service:
  name: http
  type: ClusterIP
  ports:
    internalPort: 8200
    externalPort: 8200

keyPrefix: secret/

fullnameOverride:
nameOverride:

enable_k8s_auth: true

secrets_json: |
    {
      "secret/something": "asdf"
    }

policies_json: |
  {
    "policy1": "path \"secret/*\" { policy = \"write\" }"
  }

k8sroles_json: |
  [
    {
        "name": "k8sauth",
        "service_accounts": "default",
        "namespaces": "default",
        "policies": "policy1"
    }
  ]
